### ISSUE TITLE
Build wlan example failed

### ISSUE THREAD

**Issue by Roooock** [ambiot/ambd_sdk#10]
I try to build the example of wlan, but it build failed.
Path of example code: project\realtek_amebaD_va0_example\example_sources\wlan

Fail log:
`./build/ram/main.o: In function 'main':
/cygdrive/c/Users/rock_shen/Desktop/MCU/ambd_sdk/project/realtek_amebaD_va0_example/src/src_hp/main.c:19: undefined reference to 'ReRegisterPlatformLogUart'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:358: linker_image2_ns] Error 1
make[1]: Leaving directory '/cygdrive/c/Users/rock_shen/Desktop/MCU/ambd_sdk/project/realtek_amebaD_va0_example/GCC-RELEASE/project_hp/asdk'
make: *** [Makefile:17: all] Error 2`

It seems like ReRegisterPlatformLogUart function is not found in ambd_sdk.
Could anyone help check this issue?

**Comment by xidameng** [comment]
Hi @Roooock ,

May I know your setup? Which example have you enabled? and have you edited any source code other than enabling the example?

**Comment by Roooock** [comment]
Hi @xidameng 

I just copy project\realtek_amebaD_va0_example\example_sources\wlan\src\main.c to project\realtek_amebaD_va0_example\src\src_hp

I didn't edit any source code in sdk, then use "make all" command to build it.

**Comment by xidameng** [comment]
> Hi @xidameng
> 
> I just copy project\realtek_amebaD_va0_example\example_sources\wlan\src\main.c to project\realtek_amebaD_va0_example\src\src_hp
> 
> I didn't edit any source code in sdk, then use "make all" command to build it.

Hi Thanks for the info provided, I have verified and confirmed the issue exist, will look into it now.

For now, please revert the SDK back to its original state, and `make all` using the default `main.c`, no need to edit anything.

The default firmware has already enabled majority of WLAN function through the use of AT commnad (Which you can find out more in the pdf file under `doc` folder)

**Comment by xidameng** [comment]
Hi @Roooock 

Alternatively, there are 2 other options:

1. Try [`Arduino` ](https://github.com/ambiot/ambd_arduino)SDK, there are many WLAN example readily available to run
2. Check out [this folder](https://github.com/ambiot/ambd_sdk/tree/master/component/common/example) for built-in WLAN examples that can be enabled by turning on a few macros, detailed instrucitons are inside each individual folder under `README.txt`
