### ISSUE TITLE
Does Ameba-D SDK support USB CDC ACM?

### ISSUE THREAD

**Issue by Roooock** [ambiot/ambd_sdk#12]
I want to enable USB CDC ACM on our board, I refer to this document to build the example of example_usbd_cdc_acm_tp.
Document link:
component\soc\realtek\amebad\verification\usb_otg\usbd_cdc_acm_new\readme.txt

But it build failed.
![amebad_build_failed](https://user-images.githubusercontent.com/5523365/154940865-506ec1ab-cd16-4473-8d5f-c3e218590b0d.jpg)

It seems like usbd.h is not found in ambd_sdk.
Could anyone help check this issue?

**Comment by xidameng** [comment]
hi currently, there is no USB support for this version SDK, USB support is available in the NDA SDK and might be available in this SDK in the future
