### ISSUE TITLE
Image Tool support for Linux

### ISSUE THREAD

**Issue by ubieda** [ambiot/ambd_sdk#15]
Hi all,

I'm wondering if there is any Image-Tool alternative for Linux (Ubuntu 20.04 LTS), to perform Device Fimrware Updates over UART.
I have a BW16 breakout board and am looking to load some firmware to leverage it for a project.

Thanks in advance!

Best regards,
Luis.

**Comment by M-ichae-l** [comment]
Currently for this SDK there is no linux image tool. You can find the image tool from arduino SDK, https://github.com/ambiot/ambd_arduino
