### ISSUE TITLE
no rule to make

### ISSUE THREAD

**Issue by CoderZJCC** [ambiot/ambd_sdk#19]

**Comment by S10143806H** [comment]
Hi @CoderZJCC ,

Could you please provide **detailed information (such as a log, or a screenshot of the error)** on the issue you have encountered?

Please note that you should download the released ambd_sdk from [here](https://github.com/ambiot/ambd_sdk/releases/tag/QC-V1.0.0).

I hope this could help with solving the issue you have encountered.
Thank you.

**Comment by CoderZJCC** [comment]
when i 'make menuconfig' to  enable the bt and mesh device, Compile not success, i use release 1.0.1 Version

this is the build infomation:

/Mesh/ambd_sdk/project/realtek_amebaD_va0_example/GCC-RELEASE/project_hp/asdk/../../../../../component/common/bluetooth/realtek/sdk/example/bt_mesh/api/device -I/home/zjc/work/src/project/Mesh/ambd_sdk/project/realtek_amebaD_va0_example/GCC-RELEASE/project_hp/asdk/../../../../../component/common/bluetooth/realtek/sdk/example/bt_mesh/api -I/home/zjc/work/src/project/Mesh/ambd_sdk/project/realtek_amebaD_va0_example/GCC-RELEASE/project_hp/asdk/../../../../../component/common/bluetooth/realtek/sdk/example/bt_mesh_test  /home/zjc/work/src/project/Mesh/ambd_sdk/project/realtek_amebaD_va0_example/GCC-RELEASE/project_hp/asdk/../../../../../component/common/bluetooth/realtek/sdk/bt_example_entry.c  -o /home/zjc/work/src/project/Mesh/ambd_sdk/project/realtek_amebaD_va0_example/GCC-RELEASE/project_hp/asdk/../../../../../component/common/bluetooth/realtek/sdk/bt_example_entry.o
make[4]: *** No rule to make target '/home/zjc/work/src/project/Mesh/ambd_sdk/project/realtek_amebaD_va0_example/GCC-RELEASE/project_hp/asdk/../../../../../component/common/bluetooth/realtek/sdk/example/bt_mesh/lib/cmd/mesh_data_uart.o', needed by 'CORE_TARGETS'.  Stop.
make[4]: Leaving directory '/home/zjc/work/src/project/Mesh/ambd_sdk/project/realtek_amebaD_va0_example/GCC-RELEASE/project_hp/asdk/make/rtl_bluetooth/mesh_device'
make[3]: *** [Makefile:31: all] Error 2
make[3]: Leaving directory '/home/zjc/work/src/project/Mesh/ambd_sdk/project/realtek_amebaD_va0_example/GCC-RELEASE/project_hp/asdk/make/rtl_bluetooth'
make[2]: *** [Makefile:14: all] Error 2
make[2]: Leaving directory '/home/zjc/work/src/project/Mesh/ambd_sdk/project/realtek_amebaD_va0_example/GCC-RELEASE/project_hp/asdk/make'
make[1]: *** [Makefile:242: make_subdirs] Error 2
make[1]: Leaving directory '/home/zjc/work/src/project/Mesh/ambd_sdk/project/realtek_amebaD_va0_example/GCC-RELEASE/project_hp/asdk'
make: *** [Makefile:17: all] Error 2

**Comment by S10143806H** [comment]
Hi @CoderZJCC,

**Please note that currently, `v1.0.1` is in a `pre-released` SDK in the `dev` branch.**
This means this version is unstable, and it is pending for QC. 
However, the link I provided just now was a link to `v1.0.0`, which is a released version.
We suggest you to test `make menuconfig` with the released version.

Meanwhile, I will help with verifying the issue you have mentioned.
Thank you.

**Comment by CoderZJCC** [comment]
ok，i will try the v1.0.0 version,

Thank you

**Comment by CoderZJCC** [comment]
V1.0.0 still has the problem of compilation errors. This problem seems to be that there is no **bt_mesh** folder, and I did not find the bt_mesh folder in the SDK. When the bt mesh option is selected in the configuration, it cannot be compiled successfully

**Comment by CoderZJCC** [comment]
where can i download this patch file sdk-amebad_v6.2C-RC.tar.gz

**Comment by CoderZJCC** [comment]
ok i got it,
thank you very much for your help

**Comment by S10143806H** [comment]
Hi @CoderZJCC ,
If there is no other questions, I will proceed to help with closing this issue.
Thanks.
