### ISSUE TITLE
编译耗时太久了

### ISSUE THREAD

**Issue by bealoon** [ambiot/ambd_sdk#22]
编译耗时太久了。不能把sdk跟application的编译空间分隔开么

**Comment by ambiot** [comment]
@bealoon  目前已經是把很多文檔寶成lib了. 編譯的取捨, 可以對下面的Makefile做修改(line 13 到  line 51), 來加速編譯時間.  https://github.com/ambiot/ambd_sdk/blob/dev/project/realtek_amebaD_va0_example/GCC-RELEASE/project_hp/asdk/make/Makefile
