### ISSUE TITLE
Failed to make flash

### ISSUE THREAD

**Issue by gingerologist** [ambiot/ambd_sdk#24]
OS: Ubuntu 20.04.4 LTS

In project_lp folder, `make all` succeeded. But `make flash` failed. with the following log:

```
ma@ma:/data/repo/ambd_sdk/project/realtek_amebaD_va0_example/GCC-RELEASE/project_lp$ make flash
make -C asdk gdb
make[1]: Entering directory '/data/repo/ambd_sdk/project/realtek_amebaD_va0_example/GCC-RELEASE/project_lp/asdk'
cp /data/repo/ambd_sdk/project/realtek_amebaD_va0_example/GCC-RELEASE/project_lp/asdk/gnu_utility/gnu_script/acut_loader/*  /data/repo/ambd_sdk/project/realtek_amebaD_va0_example/GCC-RELEASE/project_lp/asdk/gnu_utility/gnu_script/
cp: cannot stat '/data/repo/ambd_sdk/project/realtek_amebaD_va0_example/GCC-RELEASE/project_lp/asdk/gnu_utility/gnu_script/acut_loader/*': No such file or directory
make[1]: *** [Makefile:310: gdb] Error 1
make[1]: Leaving directory '/data/repo/ambd_sdk/project/realtek_amebaD_va0_example/GCC-RELEASE/project_lp/asdk'
make: *** [Makefile:31: flash] Error 2
```

The `cp` command failed. I checked `acut_loader` folder. It is there but is virtually empty since only one .gitkeep file is inside. No other files. This certainly looks weird. Any suggestions?

**Comment by gingerologist** [comment]
I still had no luck to make this work but I will spend more time on document and refresh the problem description with more details.

**Comment by gingerologist** [comment]
I finally figured out that `make flash` does not mean make a target blob for flash, it is acturally starting the download process via a debugger probe. So the question is totally inappropriate and based on misunderstanding. I closed it now.

**Comment by Orionxer** [comment]
Could you tell me how to resolve this problem? thanks!
