### ISSUE TITLE
自定义mesh模型

### ISSUE THREAD

**Issue by CoderZJCC** [ambiot/ambd_sdk#25]
自定义蓝牙mesh模型，但是注册后好像得不到调用，无法进入自定义的data_receive函数，总是进入
generic on off server receive回调函数

**Comment by S10143806H** [comment]
Hi @CoderZJCC,
在 GitHub 開源 ambd_sdk 中BT 相關範例沒有支持 BT Mesh。請問方便的話可以提供自定義藍牙mesh相關的代碼，我們幫忙看一下。

**Comment by S10143806H** [comment]
您好，因爲長時間沒有回復，我們將關閉這個issue。謝謝。
