### ISSUE TITLE
Ping延迟问题

### ISSUE THREAD

**Issue by Kamiwng1992** [ambiot/ambd_sdk#29]
测试发现连上Wi-Fi后, 不进行TCP通信, ping延迟基本在80ms左右
使用ATPT指令间隔50ms持续发送数据, ping延迟能稳定在5ms内, 想问下这是什么原因导致的.
数据如下:
来自 192.168.1.222 的回复: 字节=32 时间=55ms TTL=255
来自 192.168.1.222 的回复: 字节=32 时间=69ms TTL=255
来自 192.168.1.222 的回复: 字节=32 时间=85ms TTL=255
来自 192.168.1.222 的回复: 字节=32 时间=98ms TTL=255
来自 192.168.1.222 的回复: 字节=32 时间=90ms TTL=255
来自 192.168.1.222 的回复: 字节=32 时间=85ms TTL=255
来自 192.168.1.222 的回复: 字节=32 时间=93ms TTL=255
来自 192.168.1.222 的回复: 字节=32 时间=99ms TTL=255
来自 192.168.1.222 的回复: 字节=32 时间=103ms TTL=255
来自 192.168.1.222 的回复: 字节=32 时间=17ms TTL=255
来自 192.168.1.222 的回复: 字节=32 时间=3ms TTL=255
来自 192.168.1.222 的回复: 字节=32 时间=2ms TTL=255
来自 192.168.1.222 的回复: 字节=32 时间=25ms TTL=255
来自 192.168.1.222 的回复: 字节=32 时间=23ms TTL=255
来自 192.168.1.222 的回复: 字节=32 时间=30ms TTL=255
来自 192.168.1.222 的回复: 字节=32 时间=2ms TTL=255
来自 192.168.1.222 的回复: 字节=32 时间=2ms TTL=255
来自 192.168.1.222 的回复: 字节=32 时间=2ms TTL=255
来自 192.168.1.222 的回复: 字节=32 时间=2ms TTL=255
来自 192.168.1.222 的回复: 字节=32 时间=5ms TTL=255
来自 192.168.1.222 的回复: 字节=32 时间=3ms TTL=255
来自 192.168.1.222 的回复: 字节=32 时间=4ms TTL=255
来自 192.168.1.222 的回复: 字节=32 时间=2ms TTL=255
来自 192.168.1.222 的回复: 字节=32 时间=4ms TTL=255
来自 192.168.1.222 的回复: 字节=32 时间=2ms TTL=255

1.0及1.0.1 sdk测试结果一致

**Comment by Aurical** [comment]
>测试发现连上Wi-Fi后, 不进行TCP通信, ping延迟基本在80ms左右

问一下这个情况的 ping 是具体怎么测的？
一个可能是默认的省电模式，应为无线外设进入省电状态，需要 ping 的时候，换模式比较慢。
然后用 ATPT 时，因为持续发 ping 所以没进入省电模式。
可以尝试用 `wifi_conf.h` 里面的 `int wifi_disable_powersave(void);` 试试。

**Comment by Kamiwng1992** [comment]
添加wifi_disable_powersave后问题解决了, 谢谢
