### ISSUE TITLE
make flash

### ISSUE THREAD

**Issue by RomanLuchyshyn** [ambiot/ambd_sdk#30]
OS Linux (Ubuntu 20)

When I run make flash it fails with next output:

make flash 
make -C asdk gdb
make[1]: Entering directory '/home/<skip>/ambd_sdk/project/realtek_amebaD_va0_example/GCC-RELEASE/project_lp/asdk'
cp /home/<skip>/ambd_sdk/project/realtek_amebaD_va0_example/GCC-RELEASE/project_lp/asdk/gnu_utility/gnu_script/acut_loader/*  /home/<skip>ambd_sdk/project/realtek_amebaD_va0_example/GCC-RELEASE/project_lp/asdk/gnu_utility/gnu_script/
cp: cannot stat '/home/<skip>/ambd_sdk/project/realtek_amebaD_va0_example/GCC-RELEASE/project_lp/asdk/gnu_utility/gnu_script/acut_loader/*': No such file or directory
make[1]: *** [Makefile:311: gdb] Error 1
make[1]: Leaving directory '/home/<skip>/ambd_sdk/project/realtek_amebaD_va0_example/GCC-RELEASE/project_lp/asdk'

**Comment by Orionxer** [comment]
I encountered this problem too under Ubuntu 18.04.
I have tried Ubuntu 20.04 and 22.04 but the error still exists.

**Comment by S10143806H** [comment]
Hi @RomanLuchyshyn，
Seems like my method is not the final fix. You can temporarily apply the same change on your /hp folder.

For the permission denied error, please refer to the readme: 
| Please run the following command to grant the execution permission for all corresponding files:
| `chmod -R 777 {path}/project/realtek_amebaD_va0_example/GCC-RELEASE/`

![image](https://user-images.githubusercontent.com/9852678/205603145-960c64a1-a728-408b-a74a-9912a1984b52.png)

**Comment by RomanLuchyshyn** [comment]
Hi @S10143806H ,
Yes, I know it have fixed it.  But from side proper permissions should be fixed in the repo but not by user. I have already fixed a lot of such small bugs. It's too complicated fix permissions for each build.

**Comment by RomanLuchyshyn** [comment]
The next issue that I've just found is:
make flash
...
Load flash loader.
/home/<skip>/ambd_sdk/project/realtek_amebaD_va0_example/GCC-RELEASE/project_lp/asdk/gnu_utility/gnu_script/rtl_gdb_flash_write.txt:27: Error in sourced command file:
gnu_utility/gnu_script/target_FPGA.axf: No such file or directory.

**Comment by S10143806H** [comment]
Hi @RomanLuchyshyn,
I did not encounter your newly mentioned issue.
![image](https://user-images.githubusercontent.com/9852678/205809546-af1d0422-f74d-4392-8978-c8066c1668d2.png)
Upon `cd` to `\lp` folder and `make all`, the makefile direct to the `\asdk` folder and execute the commands below.
```
	make bootloader
	make copy_flashloader
```
Then execute `make flash` again, and you will find the `target_FPGA.axf`.

And if you are currently struggling to upload image from Linux system, you can try the methods [here](https://github.com/pankore/ambd_sdk_with_chip_non_NDA/tree/cmake_build/tools/AmebaD/Image_Tool_Linux) before our final bug fix.

**Comment by S10143806H** [comment]
Hi @RomanLuchyshyn,
Please refer to the final bug fix in the commit: https://github.com/ambiot/ambd_sdk/commit/be744260b9230cf01eafcc741d0bd4504cf8c59e.
I have added the necessary configuration files for `make flash` in both `\lp` and `\hp`, and verified on Windows and Linux OS.
Please update again upon test and verification.
Thanks.

**Comment by S10143806H** [comment]
Hi @RomanLuchyshyn,
Great! I will proceed to close the issue.
Thank you.
