### ISSUE TITLE
Efuse/SWD/RSIP/memory questions

### ISSUE THREAD

**Issue by radrogow** [ambiot/ambd_sdk#31]
Hello,

I'm a developer @kontakt.io, we're developing a product based on the 8720DN.
I've got some questions about the chip which were not answered in the user manual / datasheet:

1. User manual mentions AN0411 (efuse layout). Is the document available for download?
1. How does the SWD password work? How do we disable SWD access to the processor?
1. How do we enable RSIP? Where on the processor do we write the Initialization Vector (I've seen EFUSES only for the key)?
1. The datasheet mentions extension SRAM in the (0x100E_0000~0x100F_FFFF) address range. How do we use it?

> "When Bluetooth is disabled, more 64KB SRAM will be extended. This SRAM can also be accessed by both KM4 and KM0, up to 50MHz*32 bits." 
> _UM401 RTL872xD Datasheet - 4.2.3 Extension SRAM section._

Please contact me directly if this data cannot be shared publicly.

Kind Regards,
Radek

**Comment by S10143806H** [comment]
@radrogow,

Hi, our internal application engineers have already contacted you via email.

Thanks.
