### ISSUE TITLE
make flash failed in project_hp

### ISSUE THREAD

**Issue by Orionxer** [ambiot/ambd_sdk#32]
I have connected the chip using command  as tutorial said,
`/opt/SEGGER/JLink/JLinkGDBServer -device cortex-m33 -if SWD -scriptfile AP2_KM4.JLinkScript -port 2335`
![image](https://user-images.githubusercontent.com/117975206/206103460-d617cb0c-e703-4a83-878c-76db4a8eaeb8.png)
But I failed to flash the chip in another terminal(project_hp)
![image](https://user-images.githubusercontent.com/117975206/206102975-e163aeec-c12e-4722-9b60-2d3ec74763f1.png)
### **how could I fix it?**
@S10143806H Looking forward to your response!

**Comment by Aurical** [comment]
@Orionxer can you follow the process in this [post](https://forum.amebaiot.com/t/gdb-server-for-km4/1575) and try it out?

**Comment by Orionxer** [comment]
@Aurical
Finally I can flash the KM0 and KM4 project to the chip according to your recommended solution. 🎉 
![image](https://user-images.githubusercontent.com/117975206/206380425-b3fd82af-af4b-4390-a7b9-adef6f48a0cb.png)

Here is the solution from @wyy
> 1. Compile image for KM0
> 2. Compile image for KM4
> 3. Start GDB server for KM0 only
> 4. run make flash in the project_lp folder, this should upload km0_boot_all.bin and km0_km4_image2.bin
> 5. run make flash in the project_hp folder, this should upload km4_boot_all.bin and km0_km4_image2.bin
> 6. All three images are now present, reset and you should see the application code run

Hoping the official will update the tutorial to save everyone's time. Anyway I will close this issue.

Thanks for your help sincerely!
