### ISSUE TITLE
Cannot compile on macOS.

### ISSUE THREAD

**Issue by anuarrozman** [ambiot/ambd_sdk#35]
When running make command, this error appeared.

```make -C asdk image3_s
cp ./ld/rlx8721d_img3_s.ld  /Users/chanchuansoo/Anuar/ambd_sdk/project/realtek_amebaD_va0_example/GCC-RELEASE/project_hp/asdk/build/rlx8721d.ld
cat ./ld/rlx8721d_rom_symbol_acut_s.ld >> /Users/chanchuansoo/Anuar/ambd_sdk/project/realtek_amebaD_va0_example/GCC-RELEASE/project_hp/asdk/build/rlx8721d.ld
Extract toolchain
mkdir -p darwin
tar -jxvf asdk/asdk-6.5.0-darwin-newlib-build-999+-10.13.tar.bz2 -C darwin/
tar: Error opening archive: Failed to open 'asdk/asdk-6.5.0-darwin-newlib-build-999+-10.13.tar.bz2'
make[2]: *** [all] Error 1
make[1]: *** [check_toolchain] Error 2
make: *** [all] Error 2```

**Comment by S10143806H** [comment]
Hi @anuarrozman ,

The error log here indicates you are unzipping the toolchain, however, the toolchain zipped in "asdk/asdk-6.5.0-darwin-newlib-build-999+-10.13.tar.bz2" failed to be opened.

Could you please double-check whether you have assigned permission to the whole SDK by using `chmod -R /path 777` command?

Thank you.

**Comment by anuarrozman** [comment]
Hii @S10143806H ,

Thank you for your reply. Ive given full permission to the whole SDK. Incase this is the case, I'm running on a Mac.
The error still there even with full permission.

**Comment by S10143806H** [comment]
Hii @anuarrozman,

I have tried to compile the `ambd_sdk` on macOS and encountered the same error message that you have attached.

1. The error log indicates that the toolchain "asdk/asdk-6.5.0-darwin-newlib-build-999+-10.13.tar.bz2" is missing, which causes the compilation to fail.
2. Upon checking the commit history, I think `ambd_sdk` natively only supports Windows and Linux 2 OS platforms.

Unfortunately, this SDK does not support macOS yet :( 
Hope this answer helps you.

**Comment by anuarrozman** [comment]
Hi @S10143806H ,

Thank you for helping me check on this issue. I hope this SDK can support macOS soon. 

Have a nice day, thank you.
