### ISSUE TITLE
wifi promisc example incorrect.

### ISSUE THREAD

**Issue by lovexoo7** [ambiot/ambd_sdk#5]
1.when wifi enter promisc mode, frame is not only beacon frame.but in the example (wifi_promisc.c) cast to ieee80211_frame_info_t is incorrect. so type == RTW_RX_UNSUPPORT is incorrect.
2.how we can get rtw_rx_info_t data ?

**Comment by xidameng** [comment]
> 1.when wifi enter promisc mode, frame is not only beacon frame.but in the example (wifi_promisc.c) cast to ieee80211_frame_info_t is incorrect. so type == RTW_RX_UNSUPPORT is incorrect.
> 2.how we can get rtw_rx_info_t data ?

`wifi_promisc.c` is not exactly an example.... It details API available for promisc mode that's it, in fact I don't think there is a wifi_promisc mode example in this SDK, or maybe I am wrong?

**Comment by lovexoo7** [comment]
`component\common\api\at_cmd\atcmd_wifi.c` line 1432
`\component\common\api\wifi\wifi_promisc.c`

**Comment by lovexoo7** [comment]
> > 1.when wifi enter promisc mode, frame is not only beacon frame.but in the example (wifi_promisc.c) cast to ieee80211_frame_info_t is incorrect. so type == RTW_RX_UNSUPPORT is incorrect.
> > 2.how we can get rtw_rx_info_t data ?
> 
> `wifi_promisc.c` is not exactly an example.... It details API available for promisc mode that's it, in fact I don't think there is a wifi_promisc mode example in this SDK, or maybe I am wrong?

`component\common\api\at_cmd\atcmd_wifi.c line` 1432
`component\common\api\wifi\wifi_promisc.c`

i want to get the rssi of the frame,but i cant,there no RxControl or `rtw_rx_info_t` data.

**Comment by xidameng** [comment]
ok, so you mean the `ATWM` AT command... I see

**Comment by lovexoo7** [comment]
> ok, so you mean the `ATWM` AT command... I see

has any way to get the frame `RXControl` or `rtw_rx_info_t` ?

**Comment by xidameng** [comment]
> > ok, so you mean the `ATWM` AT command... I see
> 
> has any way to get the frame `RXControl` or `rtw_rx_info_t` ?

Why not use `ATWR` cmd instead? It will get you the RSSI you want

**Comment by xidameng** [comment]
Anyway, if you don't mind altering the main.c code a bit, you can actually find a lot of useful WiFi API here,

https://github.com/ambiot/ambd_sdk/blob/master/component/common/api/wifi/wifi_conf.h

**Comment by lovexoo7** [comment]
> > > ok, so you mean the `ATWM` AT command... I see
> > 
> > 
> > has any way to get the frame `RXControl` or `rtw_rx_info_t` ?
> 
> Why not use `ATWR` cmd instead? It will get you the RSSI you want

the RSSI is not only `AP`,is also can be `STA`.  `ATWR` only support AP.

**Comment by lovexoo7** [comment]
> Anyway, if you don't mind altering the main.c code a bit, you can actually find a lot of useful WiFi API here,
> 
> https://github.com/ambiot/ambd_sdk/blob/master/component/common/api/wifi/wifi_conf.h

hava checked all WiFi API, nonthing can be found about `rtw_rx_info_t`, and i think `rtw_rx_info_t` is the struct of  80211 frame rx info.but i cant get it.

**Comment by xidameng** [comment]
> > Anyway, if you don't mind altering the main.c code a bit, you can actually find a lot of useful WiFi API here,
> > https://github.com/ambiot/ambd_sdk/blob/master/component/common/api/wifi/wifi_conf.h
> 
> hava checked all WiFi API, nonthing can be found about `rtw_rx_info_t`, and i think `rtw_rx_info_t` is the struct of 80211 frame rx info.but i cant get it.

Here is what you should be looking for but probably will be a little tricky XD 

https://github.com/ambiot/ambd_sdk/tree/master/project/realtek_amebaD_va0_example/GCC-RELEASE/project_hp/asdk/lib/application

**Comment by lovexoo7** [comment]
> > > Anyway, if you don't mind altering the main.c code a bit, you can actually find a lot of useful WiFi API here,
> > > https://github.com/ambiot/ambd_sdk/blob/master/component/common/api/wifi/wifi_conf.h
> > 
> > 
> > hava checked all WiFi API, nonthing can be found about `rtw_rx_info_t`, and i think `rtw_rx_info_t` is the struct of 80211 frame rx info.but i cant get it.
> 
> Here is what you should be looking for but probably will be a little tricky XD
> 
> https://github.com/ambiot/ambd_sdk/tree/master/project/realtek_amebaD_va0_example/GCC-RELEASE/project_hp/asdk/lib/application

offical  can support ?

**Comment by xidameng** [comment]
You can find the struct info here

https://github.com/ambiot/ambd_sdk/blob/7c38fc7d2df96fe0312fe8ba5613e9fa5b95082a/component/common/drivers/wlan/realtek/include/wifi_structures.h#L234

**Comment by lovexoo7** [comment]
> You can find the struct info here
> 
> https://github.com/ambiot/ambd_sdk/blob/7c38fc7d2df96fe0312fe8ba5613e9fa5b95082a/component/common/drivers/wlan/realtek/include/wifi_structures.h#L234

this is a struct description,in the promise callback, buf point or usrdata point,nonthing about the struct data,  enable mode `RTW_PROMISC_ENABLE_4`  ` /**< Fetch all 802.11 packets & MIMO PLCP headers. Please note that the PLCP header would be struct rtw_rx_info_t defined in wifi_structures.h*/` ,descript has rx_info,but nothing in callback.
