### ISSUE TITLE
make flash fails: "....../acut_loader/*': No such file or directory"

### ISSUE THREAD

**Issue by pushtoopen** [ambiot/ambd_sdk#6]
when attempting to flash, unable to find the final items needed to flash. ran the following from a clean directory before attempting to flash:
git clone git@github.com:ambiot/ambd_sdk.git
git switch --detach V1.0.0
cd /ambd_sdk/project/realtek_amebaD_va0_example/GCC-RELEASE/
find . -type f -iname "*.sh" -exec chmod +x {} +    // this is to set all .sh scripts to executable
cd ./project_lp/
make setup
make all
cd ../project_hp/
make setup
make all
make mp

make flash
fails:

ambd_sdk/project/realtek_amebaD_va0_example/GCC-RELEASE/project_lp/asdk/gnu_utility/gnu_script/acut_loader/*': No such file or directory

full output:
"make -C asdk gdb
make[1]: Entering directory '/home/.../rtl/ambd_sdk/project/realtek_amebaD_va0_example/GCC-RELEASE/project_hp/asdk'
cp /home/.../rtl/ambd_sdk/project/realtek_amebaD_va0_example/GCC-RELEASE/project_hp/asdk/../../project_lp/asdk/gnu_utility/gnu_script/acut_loader/*  /home/.../rtl/ambd_sdk/project/realtek_amebaD_va0_example/GCC-RELEASE/project_hp/asdk/gnu_utility/gnu_script/acut_loader/
cp: cannot stat '/home/.../rtl/ambd_sdk/project/realtek_amebaD_va0_example/GCC-RELEASE/project_hp/asdk/../../project_lp/asdk/gnu_utility/gnu_script/acut_loader/*': No such file or directory
make[1]: *** [Makefile:536: gdb] Error 1
make[1]: Leaving directory '/home/.../rtl/ambd_sdk/project/realtek_amebaD_va0_example/GCC-RELEASE/project_hp/asdk'
make: *** [Makefile:31: flash] Error 2"

running OS UBUNTU 20.04

lsusb output:
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 04f2:b52c Chicony Electronics Co., Ltd Integrated Camera
Bus 001 Device 003: ID 8087:0a2b Intel Corp. 
Bus 001 Device 002: ID 0403:6001 Future Technology Devices International, Ltd FT232 Serial (UART) IC  // this is what im using to talk to the board
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

dependencies installed:
ubuntu:
sudo apt-get update
sudo apt-get install libc6-i386
sudo apt-get install libncurses5-dev
sudo apt-get install libncurses5:i386
sudo apt-get install libncurses5
sudo apt-get install make
sudo apt-get install bc\
sudo apt-get install gawk

why is the acut_loader folder empty? Is there a step im missing?

**Comment by M-ichae-l** [comment]
Current SDK is under test. Reported issues will be reviewed.
Many thanks to @pushtoopen

**Comment by M-ichae-l** [comment]
Proceed to closed the issue. Fix refer to #13
